name: context testing

on: 
  workflow_dispatch: 

jobs: 
  dump_context:
    runs-on: ubunut-latest
    steps:
      - name: pega informação do RNNNER
        run: |
           echo "Pega informações sobre a maquina que esta executando o workflow: ${{ github.runner }}"

      