name: Valida Ambiente

on: push

jobs:
  valida-ambiente:
    if: ${{ github.ref == 'staging' }}
    runs-on: ubuntu-latest
    steps: 
      - name: Verifica branch
        run: echo "Qual branch esta sendo executada: $GITHUB_REF"
  